version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    command: bundle exec rails server -b 0.0.0.0

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Online_Banking_System
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Online_Banking_System_development
